name: 'Create PR'
description: 'Create a new PR from two branches'
author: 'Patricio B.'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'